theme: jekyll-theme-cayman

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mengtaovivi.github.io/blog #改
root: /blog/ #改
permalink: :year/:month/:day/:title/

deploy:
  type: git
repository: https://github.com/mengtaovivi/blog.git #改
  branch: master
